image: node:14

cache:
  paths:
    - node_modules/

before_script:
  - npm instal

test:
  stage: test
  script:
    - npm run build
  only: 
    - branches
  except:
    - master
  
pages:
  stage: deploy
  script: npm run build
  artifacts:
    paths: 
      - public
    expire_in: 2 weeks

